name: the village idiot
favicon: null
layout_spectrum: 0.48303
typography_spectrum: 0.27674
title: The Village Idiot
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfcfc'
    - '#aaaaaa'
    - '#80ffff'
    - '#8c5662'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.8706422050017864
  rhythmicContrast: 0.75
purpose: []
