name: thevillageidiot
favicon: null
layout_spectrum: 0.8929
typography_spectrum: 0.8801530001219362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fdfcfc'
    - '#aaaaaa'
    - '#80ffff'
    - '#8c5662'
  brandStrength: 0.14086978766135871
  lightness: 0.11274778400547802
  saturation: 0.8706422050017864
  rhythmicContrast: 0.59784891968593
purpose: []
